spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/atable
    username: postgres
    password: Kergus-29410
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: postgresql
      datebase-platform: org.hibernate.dialect.PostgreSQLDialect
